---

- name: Test AS
  hosts: localhost
  collections:
    - opentelekomcloud.cloud
  tasks:

    - name: Get AS config info
      as_config_info:
      register: auto_scale

    - name: debug configs
      debug:
        var: auto_scale.as_configs

    - name: Get AS group info
      as_group_info:
      register: auto_scale

    - name: debug groups
      debug:
        var: auto_scale.as_groups
